FROM node:carbon

# Set up the environment
WORKDIR /app
ENTRYPOINT ["/app/scripts/docker_dev_entrypoint.sh"]
CMD ["node","--stack-trace-limit=1000","--stack-size=1024","bin/www"]
EXPOSE 3000

# General housekeeping
ENV DEBIAN_FRONTEND noninteractive

# Build the image
RUN apt update && apt upgrade -y && apt install git
